ampOnIcon = [[ASCII:
.....1a..........AC..........E
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
.....5c.......................
]]

ampOffIcon = [[ASCII:
.....1a.....x....AC.y.......zE
..............................
......4.......................
1..........aA..........CE.....
e.2......4.3...........h......
..............................
..............................
.......................h......
e.2......6.3..........t..q....
5..........c..........s.......
......6..................q....
......................s..t....
...x.5c....y.......z..........
]]

-- Create menu bar item
local caffeine = hs.menubar.new()

-- caffeine replacement
function setCaffeineDisplay(state)
	if state then
		-- caffeine:setIcon(ampOnIcon)
		caffeine:setTitle("☕️")
	else
		-- caffeine:setIcon(ampOffIcon)
		caffeine:setTitle("🥱")
	end
end

function caffeineClicked()
	setCaffeineDisplay(hs.caffeinate.toggle("displayIdle"))
end

if caffeine then
	caffeine:setClickCallback(caffeineClicked)
	hs.caffeinate.set("displayIdle", false) -- let sleep by default
	setCaffeineDisplay(hs.caffeinate.get("displayIdle"))
end
